In [ ]:
import torch

print( torch.__version__)
print(torch.cuda.is_available())
# print(torch.cuda.get_device_name(0))

2.5.1+cu124
False


**Creating Tensor CPU Example**

In [ ]:
import torch

first_tensor = torch.tensor([[1,2,3,9],[4,5,6,7]])
second_tensor = torch.tensor([[11,21,13,91],[14,51,61,71]])
print(first_tensor)
print(second_tensor)


tensor([[1, 2, 3, 9],
        [4, 5, 6, 7]])
tensor([[11, 21, 13, 91],
        [14, 51, 61, 71]])


In [ ]:

add_tensor = first_tensor + second_tensor
print(add_tensor)
print(add_tensor.size())


tensor([[ 12,  23,  16, 100],
        [ 18,  56,  67,  78]])
torch.Size([2, 4])


In [ ]:

sub_tensor = first_tensor - second_tensor
print(sub_tensor)
print(sub_tensor.size())

tensor([[-10, -19, -10, -82],
        [-10, -46, -55, -64]])
torch.Size([2, 4])


**Creating Tensors GPU Example**

In [ ]:
import torch
print( torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

cpu


In [ ]:
first_tensor = torch.tensor([[1,2,3,9],[4,5,6,7]], device=device)
second_tensor = torch.tensor([[11,21,13,91],[14,51,61,71]], device=device)

multi_tensor = first_tensor * second_tensor
print(multi_tensor)
print(multi_tensor.size())

tensor([[ 11,  42,  39, 819],
        [ 56, 255, 366, 497]])
torch.Size([2, 4])


**Moving Tensors from CPU to GPU**

In [ ]:
#1st way
Tensor.cuda()

#2nd Way
Tensor = Tensor.to("cuda")

#3rd way
Tensor.to("cuda:0")

NameError: name 'tensor' is not defined

**Moving Tensors from GPU to CPU**

In [ ]:
# 1st case Ten sor with required_grad = false
Tensor.cpu()

# 2nd case Tensor with required_grad = True
Tensor.detach().cpu()

NameError: name 'Tensor' is not defined

**Different ways to create tensors**

In [ ]:
import torch
import numpy as np

In [ ]:
# initialize a tensor from a python list
tensor_from_list = torch.tensor([1,2,3,4,5])
print(tensor_from_list)

# initialize a tensor from a tuple
tensor_from_tuple = torch.tensor((1,2,3,4,5))
print(tensor_from_tuple)

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


In [ ]:
# initialize a tensor from a np.array
tensor_from_array = torch.tensor(np.array([1,2,3,4,5]))
print("Tensor from array", tensor_from_array)

Tensor from array tensor([1, 2, 3, 4, 5])


In [ ]:
# Different functions for creating tensors

# torch.empty(), torch.ones(), torch.zeros()

tensor_empty = torch.empty(2,3)
print(tensor_empty)

tensor_ones = torch.ones(2,3)
print(tensor_ones)

tensor_zeros = torch.zeros(2,3)
print(tensor_zeros)
#

tensor([[6.8244e-07, 1.4580e-19, 4.5450e+30],
        [1.8524e+28, 2.1715e-18, 2.4283e-18]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# # tensors initialized  by size with random values
# returns a tensor filled with random numbers from a uniform distribution

tensor_rand_un = torch.rand(4,5)
print(tensor_rand_un)

# returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1
tensor_rand_no = torch.randn(4,5)
print(tensor_rand_no)

# returns a tensor filled with random integers generates uniformly
tensor_rand_in = torch.randint(0,10,(4,5))
print(tensor_rand_in)

tensor([[0.5324, 0.1589, 0.1971, 0.4694, 0.6109],
        [0.5883, 0.2102, 0.0138, 0.2320, 0.4963],
        [0.7478, 0.4539, 0.7635, 0.3206, 0.6523],
        [0.6996, 0.6566, 0.3642, 0.6851, 0.9621]])
tensor([[-0.3053, -1.4811, -0.2722,  0.7684, -1.6076],
        [ 1.0996,  1.0618,  1.0975,  1.5158, -1.0690],
        [-2.0803,  0.2616,  0.8359, -0.0914, -0.1082],
        [-1.3977, -1.4364,  0.0650, -1.5926, -0.2657]])
tensor([[7, 0, 6, 9, 5],
        [1, 5, 1, 6, 0],
        [7, 3, 0, 4, 9],
        [5, 9, 3, 4, 9]])


In [ ]:
# initialize a tensor of ones
tensor_ones = torch.ones_like(tensor_rand_in)
print(tensor_ones)

# initialize a tensor of zeros
tensor_zeros = torch.zeros_like(tensor_ones)
print(tensor_zeros)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


**Tensor Attributes**

Knowing device location, datatype, dimnetion, adn rank is very important

In [ ]:
first_tensor = torch.tensor([[1,2,3,9],[4,5,6,7]])
second_tensor = torch.tensor([[11,21,13,91],[14,51,61,71]])

torch.device indicates the tensor's device location

In [ ]:
first_tensor.device

device(type='cpu')

torch.dtype indicates the tensor's data type

In [ ]:
first_tensor.dtype

torch.int64

torch.shape shows the tensors dimentions

In [ ]:
first_tensor.shape

torch.Size([2, 4])

torch.ndim identifies the number of a tensor's dimentions or rank

In [ ]:
first_tensor.ndim

2

In [ ]:
second_tensor = torch.tensor([[11,21,13,91],[14,51,61,71]], dtype=torch.float32)
second_tensor.dtype

torch.float32

**Tensor Data Types**

In [ ]:
# Integer data type tensor
int_tensor=torch.tensor([[1,2,3,9],[4,5,6,7]], dtype=torch.int8)
print(int_tensor)
print(int_tensor.dtype)

tensor([[1, 2, 3, 9],
        [4, 5, 6, 7]], dtype=torch.int8)
torch.int8


In [ ]:
# Float data type
float_tensor=torch.tensor([[1,2,3,9],[4,5,6,7]], dtype=torch.float16)
print(float_tensor)
print(float_tensor.dtype)

tensor([[1., 2., 3., 9.],
        [4., 5., 6., 7.]], dtype=torch.float16)
torch.float16


In [ ]:
# short data tyoe tensor
short_tensor=torch.tensor([[1,2,3,9],[4,5,6,7]], dtype=torch.short)
print(short_tensor)
print(short_tensor.dtype)

tensor([[1, 2, 3, 9],
        [4, 5, 6, 7]], dtype=torch.int16)
torch.int16


In [ ]:
# casting a tensor to a new data type (1nd way)
first_tensor=int_tensor.float()
print(first_tensor)
print(first_tensor.dtype)

tensor([[1., 2., 3., 9.],
        [4., 5., 6., 7.]])
torch.float32


In [ ]:
# casting a tensor to a new data type (2st way)
sec_tensor=int_tensor.type(torch.float16)
print(sec_tensor)
print(sec_tensor.dtype)

tensor([[1., 2., 3., 9.],
        [4., 5., 6., 7.]], dtype=torch.float16)
torch.float16


**Creating Tesnsors from random samples**

In [ ]:
#@title torch.rand() selects random values from a uniform distribution on the interval [0-1]
# torch.rand() selects random values from a standard normal distribution

torch.manual_seed(111) # this will make generator generate same data every time
torch.rand(2,3)

tensor([[0.7156, 0.9140, 0.2819],
        [0.2581, 0.6311, 0.6001]])

In [ ]:
#@title torch.randint() selects integers generated uniformly between specified low and high values

torch.randint(0,10,(2,3))

tensor([[1, 6, 4],
        [4, 4, 9]])

**Create tensors like other tensors**

In [ ]:
#@title Create a tensor of shape (2,5) filled with ones
starting_tensors = torch.zeros(2,5)
print(starting_tensors)
print(starting_tensors.shape)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])


In [ ]:
#@title Create Tensor with the same size filled with random numbers
torch.manual_seed(111)
random_tensors = torch.rand_like(starting_tensors)
print(random_tensors)
print(random_tensors.shape)

tensor([[0.7156, 0.9140, 0.2819, 0.2581, 0.6311],
        [0.6001, 0.9312, 0.2153, 0.6033, 0.7328]])
torch.Size([2, 5])


In [ ]:
#@title Create a tensor with the same shape filled with ones
torch.ones_like(starting_tensors)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
#@title Create a tensor with the same shape filled with provided values
torch.full_like(starting_tensors, 5)

tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])

**Tensor operator**

In [ ]:
#@title Indexing 1 dim tensor example

one_dim_tensor = torch.tensor([1,2,3,4,5])
print(one_dim_tensor)
print(one_dim_tensor[1])
print(one_dim_tensor[2])
print(one_dim_tensor[2].item())

tensor([1, 2, 3, 4, 5])
tensor(2)
tensor(3)
3


In [ ]:
#@title Slicing 1 dim tensor example

# [start:end:step]

one_dim_tensor = torch.tensor([1,2,3,4,5])
print(one_dim_tensor)
print(one_dim_tensor[1:3])
print(one_dim_tensor[:3])

tensor([1, 2, 3, 4, 5])
tensor([2, 3])
tensor([1, 2, 3])


In [ ]:
#@title Indexing 2 dim tensor example
two_dim_tensor = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,30],[26,27,28,29,20]])

print(two_dim_tensor[1][3])

tensor(9)


In [ ]:
#@title Slicing 2 dim tensor example

two_dim_tensor = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,30],[26,27,28,29,20]])
print("First three element of first row: ", two_dim_tensor[0, 2:4])
print("First four element of Second row: ", two_dim_tensor[1, 2:4])

First three element of first row:  tensor([3, 4])
First four element of Second row:  tensor([8, 9])


In [ ]:
#@title use Indexing to extract data that meets some criteria
two_dim_tensor = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[16,17,18,19,30],[26,27,28,29,20]])
two_dim_tensor[two_dim_tensor<11]




tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:

#@title combining tensor


three_dim_tensor =  torch.stack((two_dim_tensor, two_dim_tensor));

print( three_dim_tensor )


tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [16, 17, 18, 19, 30],
         [26, 27, 28, 29, 20]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [16, 17, 18, 19, 30],
         [26, 27, 28, 29, 20]]])


In [ ]:
#@title Splitting tensors

first_tensor, second_tensor = torch.split(three_dim_tensor, 1, dim=0)

print(first_tensor)
print(second_tensor)


tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [16, 17, 18, 19, 30],
         [26, 27, 28, 29, 20]]])
tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [16, 17, 18, 19, 30],
         [26, 27, 28, 29, 20]]])


In [ ]:

#@title Splitting 2 - DIM tensors
torch.unbind(two_dim_tensor, dim=1)

(tensor([ 1,  6, 16, 26]),
 tensor([ 2,  7, 17, 27]),
 tensor([ 3,  8, 18, 28]),
 tensor([ 4,  9, 19, 29]),
 tensor([ 5, 10, 30, 20]))

In [ ]:
#@title Pointwise Operations / math functions

# basic math functions:  add(), mul(), div(), neg(), and true_divide()

# Functions for truncation:  ceil(), clamp(), floor(), etc.

# logical functions

a = torch.tensor([10,2,8,6,4])
b = torch.tensor([1,2,3,2,1])

print('adding tensors a and b: ', a.add(b))
print('multiplying tensors a and b: ', a.mul(b))
print('dividing tensors a and b: ', a.div(b))
print('subtracting tensors a and b: ', a.sub(b))

In [ ]:
#@title Reduction Operations

# Results in reducing the dimentionality or rank of the tensor

# includes statistical functions such as mean, median, mode etc.

In [ ]:
#@title Comparison Operations

# Compare all the values within a tensor or compare values of two different tensors

# Functions to find the minimum or maximum value, sort tensor values, test tensor status or condition, and similar

c = torch.tensor([[20.,14.,11.,8.], [3., 12., 24., 12.]])
print(c.max())
print(c.min())
print(torch.mean(c))
print(torch.median(c))
print(torch.mode(c))
print(torch.std(c))

tensor(24.)
tensor(3.)
tensor(13.)
tensor(12.)
torch.return_types.mode(
values=tensor([ 8., 12.]),
indices=tensor([3, 3]))
tensor(6.5683)


In [ ]:
#@title Linear Alzebra Operations

# PyTorch has a module called torch.linalg that contains a set of built-in linear algebra fucntions that are based on BLAS and LAPACK standardized libraries.

# Compute the dot product scalar of two 1d vector
first_torch = torch.tensor([1,2,3,9])
second_tensor = torch.tensor([11,21,13,91])

dot_product = torch.matmul(first_torch, second_tensor)
print(dot_product)

# Compute the matrix-matrix product (2D tensor) of two 2d tensors
first_2d_tensor = torch.tensor([[1,2,3,9],[4,5,6,7]])
second_2d_tensor = torch.tensor([[11,21,13,91],[14,51,61,71],[141,511,611,711],[114,151,161,171]])

result_2d_tensor = torch.matmul(first_2d_tensor, second_2d_tensor)
print(result_2d_tensor)

# Compute the a matrix product of 5 2d tensors
first_ten = torch.rand(2, 3)
second_ten = torch.rand(3, 5)
third_ten = torch.rand(5, 7)
fourth_ten = torch.rand(7, 11)
fifth_ten = torch.rand(11, 2)
torch.linalg.multi_dot((first_ten, second_ten, third_ten, fourth_ten, fifth_ten))

# Computing eigenvalues and eigenvectors

# create a 3x3 square matrix
A = torch.randn(4,4)

# print the above created matrix
print("matrix: ", A)

# compute the Eigen values and vectors of the matrix
eigenvalues, eigenvectors = torch.linalg.eigh(A)

# print the Eigen values and vectors
print("Eigen values: ", eigenvalues)
print("Eigen vectors: ", eigenvectors)

tensor(911)
tensor([[1488, 3015, 3417, 3905],
        [1758, 4462, 5150, 6182]])
matrix:  tensor([[ 1.2076,  1.3125,  1.4406, -1.6771],
        [-0.0088, -0.1027, -1.0516, -0.4410],
        [ 0.4180,  0.0018,  0.7646, -0.4020],
        [ 0.0268, -1.0073, -0.2743,  0.3182]])
Eigen values:  tensor([-0.9402,  0.4711,  1.1695,  1.4873])
Eigen vectors:  tensor([[-0.0258, -0.4770,  0.3840,  0.7902],
        [ 0.7640, -0.2608, -0.5720,  0.1454],
        [ 0.1078,  0.8251, -0.0932,  0.5468],
        [ 0.6356,  0.1542,  0.7188, -0.2355]])


In [ ]:
#@title Automatic Differentiation

# A set of techniques that allow us to compute gradients for arbitrary complex loss functions efficiently

# After we find the loss function, we calculate the derivative of the loss functiuon in terms of the parameters

# We iteratively update the weight parameters accordingly so that the loss function return the smallest possible loss

# This step is called iteratively optimization, as we use an optimizer to perform the update of parameters

# Two Steps in Training neutral network

# Forward propagation

# Backward propagation

# Every Complex function can be expressed as a composition of elementary functions

# For those elementary functions, we could apply symbolic diffrentaition, which would mean storing and manipulating symbolic forms of derivatives

# By using automatic diffrenetiation, we don't have to go through the process of simplifying the expressions

# Benefits of AD:

# instead, evaluate a given set of values

# Another benefits of automatic diffrentiation is that our function can contain if-else statements, for loops, or recursion

# Funcions f( x,y,z ) =  (x-y)*z

# Varibles x,y and z are; x=2, y=1 and z=5

# Label an intermediate variable a=x-y

# Find gradients off with regard to input variables: df/dx, df/dy, df/dz

# Calculate gradients of the loss function with respect to the weights by using chain rule


In [ ]:
#@title Define tensors

x = torch.autograd.Variable(torch.tensor([2.0]), requires_grad=True)
y = torch.autograd.Variable(torch.tensor([1.0]), requires_grad=True)
z = torch.autograd.Variable(torch.tensor([5.0]), requires_grad=True)

In [ ]:
#@title Compute gradients

# compute a
a = x - y

# define the function f
f = z - a

print("final value for function f= ", f)

#compute gradients

f.backward()

print("gradient of x= ", x.grad)
print("gradient of y= ", y.grad)
print("gradient of z= ", z.grad)

In [ ]:
#@title Numerical Differentiation

# Follow the definition of derivative

# A derivative of y with respect to x defines the rate of change of y with respect to x

# dy/dx = ( f( x-dx) - f(x) ) / dx

# Cons of numerical Differnetiation

# The computational cost, which increases as we increase the number of parameters in the loss functions

# The truncation errors

# The round-off errors



In [ ]:
#@title Symbolic Differentiation

# Used in Calculus

# Using a set or rules, meaning a set of formulas that we can apply to the loss functions to get the gradients

# The derivative of a functions f(x) = 3x^2 - 4x + 5

# When we apply the symbolic rules, we gw f(x) = 6x - 4

# cons

# is limited to the already defined symbolic diffrentiation rules

# It cannot be used for diffrentiating a given computational procedure

# The Computational costs, as it can lead to an explosion of symbolic terms

**Introduction to the DL Training Process**

**Way to build Deep learing model**
*   Supervised learning
*   Unsuperviced learning
*   semi-superviced learning

Data preparations ( Generic data, tensors ) -> ML -> outputs

**Model Development Stage**

*   Take the dataset and split it into three datasets: training data, validation data and testing data
*   When we design the model, we use training data to train its parameters

**Testing Step**

*   Perform backpropagation
*   Validate the model by passing in validation data
*   Measure model's performance against unseen data
*   Tune in hyperparameters
*   Common problem is deep learing is overfitting
*   Model becomes really good at recognizing what it has been trained on but cannot recognized examples it hasn't seen
*   To prevent that, we use a validation ser
*   Validation is a crucial step in measuring your model's performance
*   DUring this process, you can evaluate training data against validation data that was never used

**Model Deployment**

*   Save the model to the file
*   Or deploy the model to a product or service
*   The model is usually deployed to a production environment on a cloud server or to an edge device.















**Data preparation**

*   The first step in developing a deep learning model
*   Consists of loading the data, applying transforms, and batching the data using pytorch's built-in capabilities.
*   Use as exising popular academic dataset called CIFAR-10

CIFAR-10


*   Developed by researchers from the canadian institute for advanced research, or CIFAR
*   Consists of 60,00 small color photographs of objects from 10 classes
*   Divided into 50,000 training images and 10,000 test images.
*   Use python library called Torchvision; it has classes that support computer vision
*   torchvision.datasets module provided several subclasses to load image data from standard datasets such as our CIFAR-10 dataset
*   To create a training dataset using the existing CIFAR-10 dataset, we'll import the torch and then import the CIFAR-10 dataset













In [ ]:
#@title Data loading

# import libraries and dataset

import torch
from torchvision.datasets import CIFAR10
from keras.datasets import CIFAR10
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

train_data = CIFAR10(root='./train/', train=True, download=True, transform=ToTensor())
# test_data = CIFAR10(root='./test/', train=False, download=True, transform=ToTensor())

ImportError: cannot import name 'CIFAR10' from 'keras.datasets' (/usr/local/lib/python3.11/dist-packages/keras/api/datasets/__init__.py)

In [ ]:
#@title Load dataset
(trainX, trainy), (testX, testY) = CIFAR10.load_data()

# summarize loaded dataset
print('Train: X=%s, y=%s' % (trainX.shape, trainy.shape))
print('Test: X=%s, y=%s' % (testX.shape, testY.shape))

AttributeError: type object 'CIFAR10' has no attribute 'load_data'

In [ ]:
#@title Display Images

# plot first sixteen images
for i in range(0, 16):
	# define subplot
	plt.subplot(4, 4, i+1)
	# plot raw pixel data
	plt.imshow(trainX[i])
# show the figure
plt.show()

NameError: name 'plt' is not defined

In [ ]:
#@title Examine the training dataset

print(train_data.data.shape)
print(train_data.targets.shape)
print(train_data.class_to_idx)


NameError: name 'train_data' is not defined

In [ ]:
#@title Check the class labels
for i in range(len(train_data.classes)):
  print(i, train_data.classes[i])

NameError: name 'train_data' is not defined

In [ ]:
#@title Data Transforms

In [ ]:
#@title import and transform for training data set
from torchvision import transforms
from torchvision.datasets import CIFAR10
train_data_path = "./train/"
train_transforms = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.4914, 0.4822, 0.4465],
        std=[0.2023, 0.1994, 0.2010]
    )])
train_data = CIFAR10(root=train_data_path, train=True,
                      download=True, transform=train_transforms)

100%|██████████| 170M/170M [00:27<00:00, 6.19MB/s]


Extracting ./train/cifar-10-python.tar.gz to ./train/


In [ ]:
#@title Training data of first image

print(train_data[0])


In [ ]:
#@title Defining transform for testing data set
test_data_path = "./test/"
test_transforms = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.4914, 0.4822, 0.4465],
        std=[0.2023, 0.1994, 0.20])
])

test_data = CIFAR10(root=test_data_path, train=False,
                        download=True, transform=test_transforms)

100%|██████████| 170M/170M [00:06<00:00, 27.8MB/s]


Extracting ./test/cifar-10-python.tar.gz to ./test/


**Data Batching**

*   A Data loader feeds data from the dataset into the neural network
*   At the core of pytorch data loading utility is the torch.utils.data.DataLoader class

**Data Loadder Class**
Represents a python iterable over a dataset, with support for:

*   Map-style and iterable-style datasets
*   Customizing data loading order
*   Automatic batching
*   Single and multi-process data loading

1.   The Neural network trains best with batches of data
2.   Instead of using the complete datasets in one training pass, we use mini batches, usually 64 or 128 samples.
3.   Smaller batches require less memory than the entire dataset, resulting in more efficient and accelerated traing
4.   dataloader has, by default, a batch_size of 1
5.   batch_size represents a number of images that go through the network before we train and update it









In [ ]:
#@title Data batching

from torchvision import transforms
from torchvision.datasets import CIFAR10
from torch.utils.data import DataLoader
train_data_path = "./train/"
test_data_path = "./test/"
train_transforms = transforms.Compose([
    transforms.Resize(64),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.4914, 0.4822, 0.4465],
        std=[0.2023, 0.1994, 0.2010])])
training_data = CIFAR10(train_data_path, train=True, download=True, transform=train_transforms)

test_transforms = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.4914, 0.4822, 0.4465],
        std=[0.2023, 0.1994, 0.2010])])
test_data = CIFAR10(test_data_path, train=False, download=True, transform=test_transforms)

train_dataloader = DataLoader(training_data, batch_size=16, shuffle=True)
test_data_loader = DataLoader(test_data, batch_size=16, shuffle=True)

Files already downloaded and verified
Files already downloaded and verified


In [9]:
#@title Model development and training

# import libraries and dataset
import torch
from torchvision import models
from torchvision import transforms
from torchvision.datasets import CIFAR10
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
# from keras.datasets import CIFAR10
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt


# Define neural network, init and forward functions
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# instantiate the model
net = Net()

# define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
# load and transfrom the data
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

testset = CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

# Train the network

for epoch in range(10): #loop over the dataset multiple times
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameters gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        #print statistics
        running_loss += loss.item()
        if i % 2000 == 1999: # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')

100%|██████████| 170M/170M [00:04<00:00, 38.7MB/s]


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified
[1,  2000] loss: 2.191
[1,  4000] loss: 1.867
[1,  6000] loss: 1.685
[1,  8000] loss: 1.574
[1, 10000] loss: 1.535
[1, 12000] loss: 1.464
[2,  2000] loss: 1.393
[2,  4000] loss: 1.367
[2,  6000] loss: 1.355
[2,  8000] loss: 1.312
[2, 10000] loss: 1.302
[2, 12000] loss: 1.285
[3,  2000] loss: 1.227
[3,  4000] loss: 1.209
[3,  6000] loss: 1.187
[3,  8000] loss: 1.201
[3, 10000] loss: 1.193
[3, 12000] loss: 1.176
[4,  2000] loss: 1.110
[4,  4000] loss: 1.112
[4,  6000] loss: 1.120
[4,  8000] loss: 1.120
[4, 10000] loss: 1.103
[4, 12000] loss: 1.098
[5,  2000] loss: 1.040
[5,  4000] loss: 1.053
[5,  6000] loss: 1.043
[5,  8000] loss: 1.044
[5, 10000] loss: 1.047
[5, 12000] loss: 1.044
[6,  2000] loss: 0.964
[6,  4000] loss: 0.987
[6,  6000] loss: 0.980
[6,  8000] loss: 1.031
[6, 10000] loss: 1.003
[6, 12000] loss: 1.004
[7,  2000] loss: 0.895
[7,  4000] loss: 0.948
[7,  6000] loss: 0.945
[7,  8000] los

In [14]:
#@title Validation and testing

# import libraries and dataset
import torch
from torchvision import transforms
from torchvision import models
from torchvision.datasets import CIFAR10
from torch.utils.data import DataLoader
from torch.utils.data import random_split
from torch import optim
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import matplotlib.pyplot as plt


# Define neural network, init and forward functions
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# instantiate the model
net = Net()

# define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

# load and transfrom the data
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

train_transforms = transforms.Compose([ transforms.RandomCrop(32, padding=4), # Changed RandomCorp to RandomCrop
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.4914, 0.4822, 0.4465],
        std=[0.2023, 0.1994, 0.2010])])

trainset = CIFAR10(root='./train', train=True,
                                        download=True, transform=train_transforms)

train_set, value_set = random_split(trainset, [45000, 5000])

trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True)

valloader = torch.utils.data.DataLoader(value_set, batch_size=4,
                                          shuffle=True)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)
testset = CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

# Set the model for training mode and evaluation mode

for epoch in range(10): #loop over the dataset multiple times
    net.train() # set modal in training mode
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        # zero the parameters gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        #print statistics
        running_loss += loss.item()

    net.eval() # set modal for evaluation mode for validation
    validation_loss = 0.0
    correct = 0
    total = 0
    with torch.no_grad():
        for data in testloader:
            inputs, labels = data
            outputs = net(inputs)
            loss = criterion(outputs, labels)
            validation_loss += loss.item()
            _,prediction = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (prediction == labels).sum().item()
        print( f'Epoch {epoch + 1}, Traning Loss { running_loss / len(trainloader)}, Validation Loss {validation_loss / len(valloader)}, Accuracy {100 * correct / total}')

print('Finished Training')


100%|██████████| 170M/170M [00:06<00:00, 25.7MB/s]


Extracting ./train/cifar-10-python.tar.gz to ./train
Files already downloaded and verified
Epoch 1, Traning Loss 1.7661233481168748, Validation Loss 3.991722195339203, Accuracy 28.26
Epoch 2, Traning Loss 1.5174107562550903, Validation Loss 3.8430473915576933, Accuracy 33.92
Epoch 3, Traning Loss 1.4249129274564982, Validation Loss 4.381662471199036, Accuracy 27.95
Epoch 4, Traning Loss 1.3690603186619281, Validation Loss 3.9468659352302553, Accuracy 31.5
Epoch 5, Traning Loss 1.3334507009992003, Validation Loss 4.422182792663574, Accuracy 29.94
Epoch 6, Traning Loss 1.3008704982116819, Validation Loss 4.336253748822212, Accuracy 25.07
Epoch 7, Traning Loss 1.2732537155169248, Validation Loss 4.54695656247139, Accuracy 29.33
Epoch 8, Traning Loss 1.2611231256994606, Validation Loss 4.53437417602539, Accuracy 27.07
Epoch 9, Traning Loss 1.2399582139212637, Validation Loss 4.477007531476021, Accuracy 29.79
Epoch 10, Traning Loss 1.2334189281319827, Validation Loss 4.6532459534049035, Acc